### ISSUE TITLE
What Should I Do? Error running local transform~!

### ISSUE THREAD

**Issue by hutism** [shizzz477/msploitego#5]
When I transformed xml object, An error message came up.

Error running local transform: java.io.IOException:Cannot run program "/usr/bin/python" (in derectory "/root/proj/oscp-maltego/msploitego/src/msploitego/transforms"): error=2, No such file or  directory....

Please Help Me.

What Should I Do?

**Comment by shizzz477** [comment]
Ah, it looks like the path of the transform is not correct, I need to go
through them all again. In the meantime, in Maltego open the transform in
the transform manager, update the path to where your transforms are and the
working directory. The transform parameter should just be the python file
name, the working directory should be where your 'transforms' directory is.

Let me know if that worked, thanks for the feedback!
-Marc

**Comment by shizzz477** [comment]
This has been fixed and merged into master, please update.  Import the updated mtz file in Maltego and be sure all the boxes are checked so they overwrite the older version.

**Comment by hutism** [comment]
Thank you for your kind. I'll Try.
